name: build

on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          path: 'repository'
          submodules: recursive

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y make gcc-arm-none-eabi

      - name: Install gtest
        run: |
          sudo apt-get install libgtest-dev cmake                                   &&  \
          cd /usr/src/gtest                                                         &&  \
          sudo cmake CMakeLists.txt                                                 &&  \
          sudo make                                                                 &&  \
          sudo cp ./lib/libgtest*.a /usr/lib

      - run: mkdir -p repository/build/tests/stm32f103_build && cd repository/tests/stm32f103_build && make
      - run: mkdir -p repository/build/tests/stm32g0b1_build && cd repository/tests/stm32g0b1_build && make
      - run: mkdir -p repository/build/tests/gtest && cd repository/tests/gtest && make
